added the werkzeug,uuid,jwt,datetime and implenented the register fun…
alexcastillla/Plant-Care-FP-4Geeks-BACKEND pull request #7
Opened 2020-12-01 11:24 UTC by aurelianvoinea6

…ction with Get and Post

2020-12-01 13:46 UTC, JuanLGC requested changes

2020-12-01 13:46 UTC, JuanLGC commented on src/main.py
> + db.session.commit()
Esto debe ir en la logica de los modelos

2020-12-01 13:46 UTC, JuanLGC commented on src/main.py
> + return jsonify({'message': 'registered successfully'})
devuelve el objeto que has registrado

2020-12-01 13:46 UTC, JuanLGC commented on src/main.py
> +    if not auth or not auth["username"] or not auth["password"]:
tu no tienes auth, tienes body

2020-12-01 13:46 UTC, JuanLGC commented on src/main.py
> +    user = Users.query.filter_by(email=auth.username).first()
logica de los modelos

2020-12-01 13:46 UTC, JuanLGC commented on src/main.py
> +    if check_password_hash(user.password, auth.password):
igual, no tienes auth

2020-12-01 13:46 UTC, JuanLGC commented on src/main.py
> +        return jsonify({'token' : token.decode('UTF-8')})
decode?

2020-12-01 13:46 UTC, JuanLGC commented on src/main.py
> +@app.route('/users', methods=['GET'])
no te hace falta

2020-12-01 14:36 UTC, JimenaEB requested changes
Lo mismo que te he puesto con la cuenta de Juan :)

2020-12-03 16:49 UTC, JimenaEB approved these changes

2020-12-03 16:56 UTC, merged